spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gzh
    username: root
    password: 123456
  mvc:
    view:
      suffix: .html
      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

server:
  port: 80

logging:
  # 设置logback.xml位置
  config: classpath:log/logback.xml

num: 112